app = "electric-service"

[build]
  image = "electricsql/electric:latest"

[env]
  DATABASE_URL = "postgresql://postgres:jd7dnajsr3r2@db.aedtbwqxqsprgyljybuv.supabase.co:5432/postgres"
  ELECTRIC_DATABASE_USE_IPV6 = true
  ELECTRIC_SECRET = "3ee928daff08063550b7a094cbac348b74427d8eaf65003221e0ded79d53fcec"

[http_service]
  internal_port = 3000
  force_https = true

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "20s"
    method = "GET"
    path = "/v1/health"